const { app, BrowserWindow } = require('electron')
const { mkdirSync, writeFileSync } = require('node:fs')
const { join } = require('node:path')
if (process.env.HBO_PACKAGED_ROOT) {
  const resources = join(process.env.HBO_PACKAGED_ROOT, 'resources')
  Object.defineProperty(app, 'isPackaged', { value: true })
  Object.defineProperty(process, 'resourcesPath', { value: resources })
  require(join(resources, 'app.asar', 'out', 'main', 'index.js'))
} else {
  require('../out/main/index.js')
}
const delay = ms => new Promise(resolve => setTimeout(resolve, ms))
async function toggleThroughUi(win, running) {
  await win.webContents.executeJavaScript("document.querySelector('.character button').click()")
  for (let attempt=0; attempt<50; attempt++) {
    await delay(100)
    const snapshot = await win.webContents.executeJavaScript('window.hboHelper.getSnapshot()')
    if (snapshot.status.running === running && snapshot.status.phase !== 'connecting') return snapshot
  }
  throw new Error('Monitor button did not complete')
}
const deadline = setTimeout(() => { console.error('Smoke test timed out'); app.exit(1) }, 25000)
app.whenReady().then(async () => {
  await delay(500)
  const win = BrowserWindow.getAllWindows()[0]
  if (!win) throw new Error('Window missing')
  if (win.webContents.isLoading()) await new Promise(resolve => win.webContents.once('did-finish-load', resolve))
  const initial = await win.webContents.executeJavaScript("window.hboHelper.getSnapshot()")
  if (initial.sample !== null || initial.status.mode !== 'live') throw new Error('Stale or demo data at startup')
  if (await win.webContents.executeJavaScript("document.querySelector('.avatar img') !== null")) throw new Error('Unknown profession should have an empty avatar')
  const dir=join(__dirname,'../artifacts')
  mkdirSync(dir,{recursive:true})
  writeFileSync(join(dir,'dashboard-idle.png'),(await win.webContents.capturePage()).toPNG())
  const start = await toggleThroughUi(win, true)
  if (!start.status.running || !start.sample || start.status.error) throw new Error(JSON.stringify(start))
  if (start.sample.gold !== null || start.experienceSession !== 0 || start.status.intervalMs !== 5000)
    throw new Error('Unconfirmed fields or baseline are incorrect')
  if (process.env.HBO_EXPECT_CHARACTER && start.sample.character !== process.env.HBO_EXPECT_CHARACTER) throw new Error('Unexpected character')
  if (process.env.HBO_EXPECT_PROFESSION && start.sample.profession !== process.env.HBO_EXPECT_PROFESSION) throw new Error('Unexpected profession')
  const text = await win.webContents.executeJavaScript('document.body.innerText')
  if ((start.sample.character && !text.includes(start.sample.character)) ||
      (start.sample.profession && !text.includes(start.sample.profession)) || !text.includes('每 5 秒')) throw new Error('Identity or interval missing in UI')
  if (text.includes('掌握每一次成長') || !text.includes('本次監測總累計')) throw new Error('Dashboard layout was not updated')
  const liveState = await win.webContents.executeJavaScript("document.querySelector('.character').getAttribute('aria-label')")
  if (!liveState.includes('監測中')) throw new Error('Character monitor state is missing')
  if (start.sample.profession === '戰士') {
    const icon = await win.webContents.executeJavaScript("(() => { const img = document.querySelector('.avatar img'); return img && { loaded: img.complete && img.naturalWidth > 0, src: img.getAttribute('src') }; })()")
    if (!icon?.loaded || !icon.src.includes('warrior-')) throw new Error('Packaged warrior icon did not load')
  }
  await delay(2200)
  const beforeInterval = await win.webContents.executeJavaScript("window.hboHelper.getSnapshot()")
  if (beforeInterval.sample.timestamp !== start.sample.timestamp) throw new Error('Sample occurred before five seconds')
  await delay(3400)
  const running = await win.webContents.executeJavaScript("window.hboHelper.getSnapshot()")
  if (!running.status.running || running.sample.timestamp <= start.sample.timestamp) throw new Error('No fresh updates')
  const isolation = await win.webContents.executeJavaScript("typeof require")
  if (isolation !== 'undefined') throw new Error('Renderer is not isolated')
  const stopped = await toggleThroughUi(win, false)
  if (stopped.status.running) throw new Error('Monitor did not stop')
  await delay(100)
  const stoppedState = await win.webContents.executeJavaScript("document.querySelector('.character').getAttribute('aria-label')")
  if (!stoppedState.includes('已停止')) throw new Error('Character monitor state did not stop')
  writeFileSync(join(dir,'dashboard-stopped.png'),(await win.webContents.capturePage()).toPNG())
  await delay(5200)
  const stillStopped = await win.webContents.executeJavaScript("window.hboHelper.getSnapshot()")
  if (stillStopped.sample.timestamp !== stopped.sample.timestamp) throw new Error('Stopped monitor kept sampling')
  const restarted = await toggleThroughUi(win, true)
  if (!restarted.status.running || restarted.sample.timestamp <= running.sample.timestamp ||
      restarted.experienceSession !== 0 || restarted.startedAt <= start.startedAt)
    throw new Error('Restart did not synchronize a new baseline')
  await delay(200)
  writeFileSync(join(dir,'dashboard-live.png'),(await win.webContents.capturePage()).toPNG())
  win.setSize(880,860)
  await delay(200)
  const overflow = await win.webContents.executeJavaScript('document.documentElement.scrollWidth > window.innerWidth')
  if (overflow) throw new Error('Dashboard overflows minimum window width')
  writeFileSync(join(dir,'dashboard-narrow.png'),(await win.webContents.capturePage()).toPNG())
  console.log(JSON.stringify({result:'PASS', character:restarted.sample.character, profession:restarted.sample.profession, intervalMs:restarted.status.intervalMs, firstExperience:start.sample.experience, latestExperience:restarted.sample.experience, level:restarted.sample.level, threshold:restarted.sample.experienceRequired, processId:restarted.sample.processId, restartSynchronized:true}))
  clearTimeout(deadline)
  app.quit()
}).catch(error => { console.error(error); clearTimeout(deadline); app.exit(1) })
