const { app, BrowserWindow } = require('electron')
const { mkdirSync, writeFileSync } = require('node:fs')
const { join } = require('node:path')
require('../out/main/index.js')
const delay = ms => new Promise(resolve => setTimeout(resolve, ms))
const deadline = setTimeout(() => { console.error('Smoke test timed out'); app.exit(1) }, 25000)
app.whenReady().then(async () => {
  await delay(500)
  const win = BrowserWindow.getAllWindows()[0]
  if (!win) throw new Error('Window missing')
  if (win.webContents.isLoading()) await new Promise(resolve => win.webContents.once('did-finish-load', resolve))
  const initial = await win.webContents.executeJavaScript("window.hboHelper.getSnapshot()")
  if (initial.sample !== null || initial.status.mode !== 'live') throw new Error('Stale or demo data at startup')
  const start = await win.webContents.executeJavaScript("window.hboHelper.start()")
  if (!start.status.running || !start.sample || start.status.error) throw new Error(JSON.stringify(start))
  if (start.sample.gold !== null || start.sample.character !== null || start.experienceSession !== 0)
    throw new Error('Unconfirmed fields or baseline are incorrect')
  await delay(2200)
  const running = await win.webContents.executeJavaScript("window.hboHelper.getSnapshot()")
  if (!running.status.running || running.sample.timestamp <= start.sample.timestamp) throw new Error('No fresh updates')
  const isolation = await win.webContents.executeJavaScript("typeof require")
  if (isolation !== 'undefined') throw new Error('Renderer is not isolated')
  await win.webContents.executeJavaScript("window.hboHelper.stop()")
  const stopped = await win.webContents.executeJavaScript("window.hboHelper.getSnapshot()")
  if (stopped.status.running) throw new Error('Monitor did not stop')
  const restarted = await win.webContents.executeJavaScript("window.hboHelper.start()")
  if (!restarted.status.running || restarted.sample.timestamp <= running.sample.timestamp ||
      restarted.experienceSession !== 0 || restarted.startedAt <= start.startedAt)
    throw new Error('Restart did not synchronize a new baseline')
  const dir=join(__dirname,'../artifacts')
  mkdirSync(dir,{recursive:true})
  await delay(200)
  writeFileSync(join(dir,'dashboard-live.png'),(await win.webContents.capturePage()).toPNG())
  console.log(JSON.stringify({result:'PASS', firstExperience:start.sample.experience, latestExperience:restarted.sample.experience, level:restarted.sample.level, threshold:restarted.sample.experienceRequired, processId:restarted.sample.processId, restartSynchronized:true}))
  clearTimeout(deadline)
  app.quit()
}).catch(error => { console.error(error); clearTimeout(deadline); app.exit(1) })
